name: Running tests

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1

      - run: yarn && yarn compile
      - run: yarn release
